export const colorsConstants = [
  {
    id: 0,
    main: "#4169E1",
    second: "#F5F7FE",
    third: "#EDEFF6",
    fourth: "#c1c8db",
  },
  {
    id: 1,
    main: "#59A4B2",
    second: "#F2F8F9",
    third: "#EEF2F3",
    fourth: "#c1dadf",
  },
  {
    id: 2,
    main: "#BD89C9",
    second: "#F2EDF3",
    third: "#F7F2F7",
    fourth: "#d2bed6",
  },
  {
    id: 3,
    main: "#1F3F6F",
    second: "#E5E7EB",
    third: "#EDEFF1",
    fourth: "#c0cbda",
  },
  {
    id: 4,
    main: "#798CA9",
    second: "#EAECEF",
    third: "#F0F1F2",
    fourth: "#bcc6d5",
  },
  {
    id: 5,
    main: "#7258D2",
    second: "#EEECF4",
    third: "#EAE9F0",
    fourth: "#c0bcd0",
  },
  {
    id: 6,
    main: "#D1794A",
    second: "#F4EEEA",
    third: "#f1ece6",
    fourth: "#e2cec3",
  },
  {
    id: 7,
    main: "#f759ab",
    second: "#fcf3f8",
    third: "#f1ece6",
    fourth: "#e2c8d5",
  },
];
